// Generated by CoffeeScript 1.7.1
require(['jquery.smoothscroll', 'bootstrap-tab', 'jquery.oddify'], function($) {
  $('.pagetop a').smoothscroll();
  $('.subnav a').smoothscroll({
    offset: -50
  });
  $('#menu1 a').tab('show');
  $('#menu a').on('shown', function() {
    return $('html, body').scrollTop(0);
  });
  return $(".chart").oddify();
});
