// Generated by CoffeeScript 1.7.1
(function() {
  var dest, redirectUrlFromFacebook, url;
  redirectUrlFromFacebook = "" + location.protocol + "//" + location.host + "/e/07DWlsY1N" + location.search;
  dest = encodeURIComponent(redirectUrlFromFacebook);
  url = "https://www.facebook.com/dialog/oauth/?client_id=335292516550203&redirect_uri=" + dest + "&scope=user_birthday,email";
  window.top.location = url;
}).call(this);
