// Generated by CoffeeScript 1.7.1
var jQueryPluginShim;
jQueryPluginShim = {
  deps: ['jquery'],
  exports: 'jQuery'
};
requirejs.config({
  baseUrl: '/static/js/',
  waitSeconds: 0,
  paths: {
    jquery: 'libs/jquery/jquery-1.8.2.min',
    'picturefill': 'libs/picturefill',
    'jquery.countdown': 'libs/jquery/jquery.countdown',
    'jquery.dropdown': 'libs/jquery/jquery.dropdown',
    'jquery.autofilladdress': 'libs/jquery/jquery.autofilladdress',
    'jquery.cookie': 'libs/jquery/jquery.cookie',
    'jquery.lazyload': 'libs/jquery/jquery.lazyload.min',
    'bootstrap-tooltip': 'libs/jquery/bootstrap-tooltip',
    'bootstrap-modal': 'libs/jquery/bootstrap-modal',
    underscore: 'libs/underscore/underscore-min',
    backbone: 'libs/backbone/backbone',
    hbs: 'libs/require-handlebars-plugin/hbs'
  },
  shim: {
    underscore: {
      exports: '_'
    },
    backbone: {
      deps: ['underscore', 'jquery'],
      exports: 'Backbone'
    },
    'jquery.cookie': jQueryPluginShim,
    'jquery.lazyload': jQueryPluginShim,
    'jquery.dropdown': jQueryPluginShim,
    'bootstrap-tooltip': jQueryPluginShim,
    'bootstrap-modal': jQueryPluginShim
  }
});
